
SOURCES = left.scad right.scad shelf.scad

include ../common/stl.mk

left.openscad.stl : shelf.scad copies.scad shapes.scad
right.openscad.stl : shelf.scad copies.scad shapes.scad
shelf.openscad.stl : copies.scad shapes.scad

# The end.
