
SOURCES = \
	  hold-down-clamp.scad \
	  pcb-hold-down.scad \
	  pcb-work-bracket.scad

include ../common/stl.mk

hold-down-clamp.openscad.stl :
pcb-hold-down.openscad.stl :
pcb-work-bracket.openscad.stl : ../common/threads.scad

# The end.
