
SOURCES = adapter.scad adapter_1_75.scad adapter_2_85.scad adapter_extruder.scad

include ../common/stl.mk

adapter_1_75.openscad.stl : adapter.scad
adapter_2_85.openscad.stl : adapter.scad
adapter_extruder.openscad.stl : adapter.scad

# The end.
