
SOURCES = \
	  xcarve-stand-left.scad \
	  xcarve-stand-pad.scad \
	  xcarve-stand-right.scad

include ../common/stl.mk

xcarve-stand-left.openscad.stl : xcarve-stand.scad
xcarve-stand-pad.openscad.stl : xcarve-stand.scad
xcarve-stand-right.openscad.stl : xcarve-stand.scad

# The end.
