
SOURCES = bear-plaque.scad zoe-plaque.scad

include ../common/stl.mk

bear-plaque.openscad.stl : utils.scad magnetic-plaque.scad shapes.scad
magnetic-plaque.openscad.stl : shapes.scad
zoe-plaque.openscad.stl : utils.scad magnetic-plaque.scad shapes.scad

# The end.
