
SOURCES = bore.scad gears.scad speed_holes.scad

include ../common/stl.mk

bore.openscad.stl : units.scad
gears.openscad.stl : copies.scad
speed_holes.openscad.stl : copies.scad units.scad

# The end.
